package cn.tedu.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import cn.tedu.entity.Address;

@Mapper
public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    Address selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    int updateByPrimaryKey(Address record);
    /**
     * 根据用户查询默认
     * @param uid
     * @return
     */
    Address findByDefault(Integer uid);
    
    /**
     * 查询用户的所有收获地址
     * @param uid
     * @return
     */
    List<Address> findByUid(Integer uid);
    
    /**
     * 将全部设置为非默认
     * @param uid
     * @return
     */
    Integer setNoDefault(Integer uid);
    /**
     * 将指定收获地址变成默认
     * @param uid
     * @param aid
     * @return
     */
    Integer setOneDefault(@Param("uid")Integer uid,@Param("aid")Integer aid);
}