package cn.tedu.mapper;

import org.apache.ibatis.annotations.Mapper;

import cn.tedu.entity.GoodsCategory;

@Mapper
public interface GoodsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    int insert(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    int insertSelective(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    GoodsCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_category
     *
     * @mbg.generated Sat Nov 30 18:24:06 CST 2019
     */
    int updateByPrimaryKey(GoodsCategory record);
}