package cn.tedu.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import cn.tedu.entity.User;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Nov 30 19:42:58 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Nov 30 19:42:58 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Nov 30 19:42:58 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Nov 30 19:42:58 CST 2019
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Nov 30 19:42:58 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Nov 30 19:42:58 CST 2019
     */
    int updateByPrimaryKey(User record);
    
    /**
     * 根据用户名查询
     * @param username
     * @return
     */
    User findByUsername(String username);
    
    /**
     * 修改密码
     */										
    Integer changePassword(@Param("password")String password,@Param("uid")Integer uid);
    
    
    /**
     * 修改头像地址
     */
    Integer changeAvatar(@Param("avatar")String avatar,@Param("uid")Integer uid);
    
}