package cn.tedu.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *  ’ªıµÿ÷∑
 *
 */
public class Address implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -7012467901513282980L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.aid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer aid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.uid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.province
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.city
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.area
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.district
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String district;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.zip
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String zip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.phone
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.tel
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.tag
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String tag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.is_default
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer isDefault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String modifiedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_address.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date modifiedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.aid
	 * @return  the value of t_address.aid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getAid() {
		return aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.aid
	 * @param aid  the value for t_address.aid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setAid(Integer aid) {
		this.aid = aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.uid
	 * @return  the value of t_address.uid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.uid
	 * @param uid  the value for t_address.uid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.name
	 * @return  the value of t_address.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.name
	 * @param name  the value for t_address.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.province
	 * @return  the value of t_address.province
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.province
	 * @param province  the value for t_address.province
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.city
	 * @return  the value of t_address.city
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.city
	 * @param city  the value for t_address.city
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.area
	 * @return  the value of t_address.area
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.area
	 * @param area  the value for t_address.area
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.district
	 * @return  the value of t_address.district
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getDistrict() {
		return district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.district
	 * @param district  the value for t_address.district
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setDistrict(String district) {
		this.district = district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.zip
	 * @return  the value of t_address.zip
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.zip
	 * @param zip  the value for t_address.zip
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.address
	 * @return  the value of t_address.address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.address
	 * @param address  the value for t_address.address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.phone
	 * @return  the value of t_address.phone
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.phone
	 * @param phone  the value for t_address.phone
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.tel
	 * @return  the value of t_address.tel
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.tel
	 * @param tel  the value for t_address.tel
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.tag
	 * @return  the value of t_address.tag
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.tag
	 * @param tag  the value for t_address.tag
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.is_default
	 * @return  the value of t_address.is_default
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getIsDefault() {
		return isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.is_default
	 * @param isDefault  the value for t_address.is_default
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setIsDefault(Integer isDefault) {
		this.isDefault = isDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.created_user
	 * @return  the value of t_address.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.created_user
	 * @param createdUser  the value for t_address.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.created_time
	 * @return  the value of t_address.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.created_time
	 * @param createdTime  the value for t_address.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.modified_user
	 * @return  the value of t_address.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.modified_user
	 * @param modifiedUser  the value for t_address.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_address.modified_time
	 * @return  the value of t_address.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_address.modified_time
	 * @param modifiedTime  the value for t_address.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Override
	public String toString() {
		return "Address [aid=" + aid + ", uid=" + uid + ", name=" + name + ", province=" + province + ", city=" + city
				+ ", area=" + area + ", district=" + district + ", zip=" + zip + ", address=" + address + ", phone="
				+ phone + ", tel=" + tel + ", tag=" + tag + ", isDefault=" + isDefault + ", createdUser=" + createdUser
				+ ", createdTime=" + createdTime + ", modifiedUser=" + modifiedUser + ", modifiedTime=" + modifiedTime
				+ "]";
	}
	
	
}