package cn.tedu.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 *¹ºÎï³µ
 */
public class Cart implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 2109907623448102452L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart.cid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart.uid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart.gid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Long gid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart.num
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String modifiedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cart.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date modifiedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart.cid
	 * @return  the value of t_cart.cid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart.cid
	 * @param cid  the value for t_cart.cid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart.uid
	 * @return  the value of t_cart.uid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart.uid
	 * @param uid  the value for t_cart.uid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart.gid
	 * @return  the value of t_cart.gid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Long getGid() {
		return gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart.gid
	 * @param gid  the value for t_cart.gid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setGid(Long gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart.num
	 * @return  the value of t_cart.num
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart.num
	 * @param num  the value for t_cart.num
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart.created_user
	 * @return  the value of t_cart.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart.created_user
	 * @param createdUser  the value for t_cart.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart.created_time
	 * @return  the value of t_cart.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart.created_time
	 * @param createdTime  the value for t_cart.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart.modified_user
	 * @return  the value of t_cart.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart.modified_user
	 * @param modifiedUser  the value for t_cart.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cart.modified_time
	 * @return  the value of t_cart.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cart.modified_time
	 * @param modifiedTime  the value for t_cart.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Override
	public String toString() {
		return "Cart [cid=" + cid + ", uid=" + uid + ", gid=" + gid + ", num=" + num + ", createdUser=" + createdUser
				+ ", createdTime=" + createdTime + ", modifiedUser=" + modifiedUser + ", modifiedTime=" + modifiedTime
				+ "]";
	}
	
	
}