package cn.tedu.entity;

import java.io.Serializable;

/**
 * 
 *µØÇø
 */
public class District implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 2207824862130752516L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_dict_district.id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_dict_district.parent
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String parent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_dict_district.code
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_dict_district.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_dict_district.id
	 * @return  the value of t_dict_district.id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_dict_district.id
	 * @param id  the value for t_dict_district.id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_dict_district.parent
	 * @return  the value of t_dict_district.parent
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getParent() {
		return parent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_dict_district.parent
	 * @param parent  the value for t_dict_district.parent
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setParent(String parent) {
		this.parent = parent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_dict_district.code
	 * @return  the value of t_dict_district.code
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_dict_district.code
	 * @param code  the value for t_dict_district.code
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_dict_district.name
	 * @return  the value of t_dict_district.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_dict_district.name
	 * @param name  the value for t_dict_district.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "District [id=" + id + ", parent=" + parent + ", code=" + code + ", name=" + name + "]";
	}
	
	
}