package cn.tedu.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 *
 */
public class GoodsCategory implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 6304654988620544379L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_category.id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_category.parent_id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Long parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_category.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_category.status
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_category.sort_order
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_category.is_parent
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer isParent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_category.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_category.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date modifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_category.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_category.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String modifiedUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_category.id
	 * @return  the value of t_goods_category.id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_category.id
	 * @param id  the value for t_goods_category.id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_category.parent_id
	 * @return  the value of t_goods_category.parent_id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_category.parent_id
	 * @param parentId  the value for t_goods_category.parent_id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_category.name
	 * @return  the value of t_goods_category.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_category.name
	 * @param name  the value for t_goods_category.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_category.status
	 * @return  the value of t_goods_category.status
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_category.status
	 * @param status  the value for t_goods_category.status
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_category.sort_order
	 * @return  the value of t_goods_category.sort_order
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_category.sort_order
	 * @param sortOrder  the value for t_goods_category.sort_order
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_category.is_parent
	 * @return  the value of t_goods_category.is_parent
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getIsParent() {
		return isParent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_category.is_parent
	 * @param isParent  the value for t_goods_category.is_parent
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setIsParent(Integer isParent) {
		this.isParent = isParent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_category.created_time
	 * @return  the value of t_goods_category.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_category.created_time
	 * @param createdTime  the value for t_goods_category.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_category.modified_time
	 * @return  the value of t_goods_category.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_category.modified_time
	 * @param modifiedTime  the value for t_goods_category.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_category.created_user
	 * @return  the value of t_goods_category.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_category.created_user
	 * @param createdUser  the value for t_goods_category.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_category.modified_user
	 * @return  the value of t_goods_category.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_category.modified_user
	 * @param modifiedUser  the value for t_goods_category.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	@Override
	public String toString() {
		return "GoodsCategory [id=" + id + ", parentId=" + parentId + ", name=" + name + ", status=" + status
				+ ", sortOrder=" + sortOrder + ", isParent=" + isParent + ", createdTime=" + createdTime
				+ ", modifiedTime=" + modifiedTime + ", createdUser=" + createdUser + ", modifiedUser=" + modifiedUser
				+ "]";
	}
	
	
}