package cn.tedu.entity;

import java.io.Serializable;
import java.util.Date;

public class Goods implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1973429679176886218L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.category_id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Long categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.item_type
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String itemType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.title
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.sell_point
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String sellPoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.price
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Long price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.num
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.barcode
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String barcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.image
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String image;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.status
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.priority
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date modifiedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String modifiedUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.id
	 * @return  the value of t_goods.id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.id
	 * @param id  the value for t_goods.id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.category_id
	 * @return  the value of t_goods.category_id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Long getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.category_id
	 * @param categoryId  the value for t_goods.category_id
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.item_type
	 * @return  the value of t_goods.item_type
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getItemType() {
		return itemType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.item_type
	 * @param itemType  the value for t_goods.item_type
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.title
	 * @return  the value of t_goods.title
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.title
	 * @param title  the value for t_goods.title
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.sell_point
	 * @return  the value of t_goods.sell_point
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getSellPoint() {
		return sellPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.sell_point
	 * @param sellPoint  the value for t_goods.sell_point
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setSellPoint(String sellPoint) {
		this.sellPoint = sellPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.price
	 * @return  the value of t_goods.price
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.price
	 * @param price  the value for t_goods.price
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.num
	 * @return  the value of t_goods.num
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.num
	 * @param num  the value for t_goods.num
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.barcode
	 * @return  the value of t_goods.barcode
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getBarcode() {
		return barcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.barcode
	 * @param barcode  the value for t_goods.barcode
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.image
	 * @return  the value of t_goods.image
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.image
	 * @param image  the value for t_goods.image
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.status
	 * @return  the value of t_goods.status
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.status
	 * @param status  the value for t_goods.status
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.priority
	 * @return  the value of t_goods.priority
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.priority
	 * @param priority  the value for t_goods.priority
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.created_time
	 * @return  the value of t_goods.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.created_time
	 * @param createdTime  the value for t_goods.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.modified_time
	 * @return  the value of t_goods.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.modified_time
	 * @param modifiedTime  the value for t_goods.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.created_user
	 * @return  the value of t_goods.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.created_user
	 * @param createdUser  the value for t_goods.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods.modified_user
	 * @return  the value of t_goods.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods.modified_user
	 * @param modifiedUser  the value for t_goods.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	@Override
	public String toString() {
		return "Goods [id=" + id + ", categoryId=" + categoryId + ", itemType=" + itemType + ", title=" + title
				+ ", sellPoint=" + sellPoint + ", price=" + price + ", num=" + num + ", barcode=" + barcode + ", image="
				+ image + ", status=" + status + ", priority=" + priority + ", createdTime=" + createdTime
				+ ", modifiedTime=" + modifiedTime + ", createdUser=" + createdUser + ", modifiedUser=" + modifiedUser
				+ "]";
	}
	
	
}