package cn.tedu.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 *
 */
public class Order implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1061422988570272809L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.oid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer oid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.uid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.phone
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.status
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.price
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Long price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.order_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date orderTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.pay_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String createdUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private String modifiedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	private Date modifiedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.oid
	 * @return  the value of t_order.oid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getOid() {
		return oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.oid
	 * @param oid  the value for t_order.oid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setOid(Integer oid) {
		this.oid = oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.uid
	 * @return  the value of t_order.uid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.uid
	 * @param uid  the value for t_order.uid
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.name
	 * @return  the value of t_order.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.name
	 * @param name  the value for t_order.name
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.phone
	 * @return  the value of t_order.phone
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.phone
	 * @param phone  the value for t_order.phone
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.address
	 * @return  the value of t_order.address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.address
	 * @param address  the value for t_order.address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.status
	 * @return  the value of t_order.status
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.status
	 * @param status  the value for t_order.status
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.price
	 * @return  the value of t_order.price
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.price
	 * @param price  the value for t_order.price
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setPrice(Long price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.order_time
	 * @return  the value of t_order.order_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getOrderTime() {
		return orderTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.order_time
	 * @param orderTime  the value for t_order.order_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.pay_time
	 * @return  the value of t_order.pay_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.pay_time
	 * @param payTime  the value for t_order.pay_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.created_user
	 * @return  the value of t_order.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getCreatedUser() {
		return createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.created_user
	 * @param createdUser  the value for t_order.created_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.created_time
	 * @return  the value of t_order.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.created_time
	 * @param createdTime  the value for t_order.created_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.modified_user
	 * @return  the value of t_order.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public String getModifiedUser() {
		return modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.modified_user
	 * @param modifiedUser  the value for t_order.modified_user
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.modified_time
	 * @return  the value of t_order.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public Date getModifiedTime() {
		return modifiedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.modified_time
	 * @param modifiedTime  the value for t_order.modified_time
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Override
	public String toString() {
		return "Order [oid=" + oid + ", uid=" + uid + ", name=" + name + ", phone=" + phone + ", address=" + address
				+ ", status=" + status + ", price=" + price + ", orderTime=" + orderTime + ", payTime=" + payTime
				+ ", createdUser=" + createdUser + ", createdTime=" + createdTime + ", modifiedUser=" + modifiedUser
				+ ", modifiedTime=" + modifiedTime + "]";
	}
	
	
}