package cn.tedu.mapper;

import cn.tedu.entity.Address;

public interface AddressMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int deleteByPrimaryKey(Integer aid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int insert(Address record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int insertSelective(Address record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	Address selectByPrimaryKey(Integer aid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int updateByPrimaryKeySelective(Address record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_address
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int updateByPrimaryKey(Address record);
}