package cn.tedu.mapper;

import cn.tedu.entity.OrderItem;

public interface OrderItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_item
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_item
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int insert(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_item
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int insertSelective(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_item
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	OrderItem selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_item
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int updateByPrimaryKeySelective(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order_item
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int updateByPrimaryKey(OrderItem record);
}