package cn.tedu.mapper;

import cn.tedu.entity.Order;

public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int deleteByPrimaryKey(Integer oid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int insertSelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	Order selectByPrimaryKey(Integer oid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int updateByPrimaryKeySelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Nov 30 19:42:58 CST 2019
	 */
	int updateByPrimaryKey(Order record);
}